name: ReadIt
on:
  push:
    branches: [ 'main', 'develop', 'release-*' ]
jobs:
  Server:
    name: Test - Unit & Integration & SonarCloud Scan
    runs-on: ubuntu-latest # macos-latest macos-11 windows-2019 ubuntu-20.04
    defaults:
      run:
        working-directory: readit-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with: { fetch-depth: 0 }

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Unit & Integration Tests
        run: mvn -B verify # -B: --batch-mode

      - name: Sonar
        if: success() # always() failure() success()
        run: >
           mvn -B verify -DskipTests sonar:sonar
           -Dsonar.projectKey=isadiamar_readit
           -Dsonar.organization=isadiamar124
           -Dsonar.host.url=https://sonarcloud.io
           -Dsonar.login=$SONAR_TOKEN
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Deploy Heroku
        if: github.ref == 'refs/heads/main'
        uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_email: "isabel.d.m@outlook.com"
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ri-readit-app" #Must be unique in Heroku


  Client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: readit-frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Test Cypress
        uses: cypress-io/github-action@v2
        with:
            working-directory: ./readit-frontend
            build: npm run build
            start: npm start
            wait-on: 'http://localhost:4200'
            wait-on-timeout: 120
        timeout-minutes: 15



